x-service-templates:
  backend: &backend
    image: zanfranceschi/rinha-de-backend-2025-csharp-exemplo
    depends_on:
      - db
    networks:
      - payment-processor
      - backend
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "50MB"
    environment:
      #- TRY_PAYMENT_METHOD=WithDefaultFirst
      - TRY_PAYMENT_METHOD=WithAvailabilityCheck
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_CONNECTION_STRING=Host=db;Port=5432;Username=postgres;Password=postgres;Database=rinha

services:
  db:
    image: postgres:17-alpine
    container_name: database
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "230MB"

  backend-01:
    <<: *backend
    container_name: backend-01
    hostname: backend-01

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02
  
  lb:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
